# Generated by Django 4.0 on 2021-12-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=70)),
                ('mobile', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=70)),
            ],
        ),
    ]
